config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see
  # http://guides.rubyonrails.org/routing.html

  root to: 'dashboard#index'

  get 'dashboard/index'

  resources :quizzes, only: [:index]
  resources :qnas
  resources :tags

  resources :yodatepicker, only: [:index]

  resources :yayplus1, only: [:index]

  mount Resque::Server, at: '/resque'

  resources :highlighter, only: [:index] do
    collection do
      post :rouge
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/qna.rb
class Qna < ApplicationRecord
  validates :question, presence: true
  validates :answer_1, presence: true
  validates :correct_answer, presence: true

  has_many_attached :images

  has_many :tag_targets, as: :target, dependent: :destroy
  has_many :tags, through: :tag_targets

  after_initialize :set_defaults, unless: :persisted?

  def set_defaults
    self.correct_answer ||= 'answer_1'
  end
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  validates :name, presence: true
end

app/models/source_code.rb
class SourceCode < ApplicationRecord
  validates :language, presence: true

  def self.rougify(language, text)
    # class method
    formatter = Rouge::Formatters::HTML.new(css_class: 'highlight-github')
    lexer = Rouge::Lexer.find(language)
    formatter.format(lexer.lex(text))
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :tag_targets

  validates :name, presence: true

  def self.search_by_name(search_params)
    if search_params[:name].present?
      table = Tag.arel_table
      where(table[:name].matches("%#{search_params[:name]}%"))
    end
  end
end

app/models/tag_target.rb
class TagTarget < ActiveRecord::Base
  belongs_to :tag
  belongs_to :target, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index; end
end

app/controllers/highlighter_controller.rb
class HighlighterController < ApplicationController
  protect_from_forgery with: :null_session

  def index; end

  def rouge
    text = rouge_params[:text]
    language = rouge_params[:language]

    # use a background job and just save to the database.
    Resque.enqueue(CodeStore, language, text)

    # Fun with a mailer, let someone know we did some work.
    # Disabled for now because in production google blocks it.
    # HighlighterMailer.syntax_highlighted.deliver_later

    result = { highlighted_text: SourceCode.rougify(language, text) }
    render json: result
  end

  private

  def rouge_params
    params.permit(:language, :text)
  end
end

app/controllers/qnas_controller.rb
class QnasController < ApplicationController
  protect_from_forgery except: [:update]

  def index
    @qnas = Qna.all.order(question: :asc)
    respond_to :html
  end

  def create
    # Can we make this create also create TagTargets?  Use nested attributes?
    @qna = Qna.create!(qna_params)

    tags = Tag.where(id: qna_params[:tag_ids])
    targets = tags.each_with_object([]) do |t, r|
      r << { tag_id: t.id, target_type: 'Qna', target_id: @qna.id }
    end
    TagTarget.create!(targets)

    redirect_to "#{qnas_path}"
  end

  def update
    @qna = Qna.find(params[:id])
    @qna.images.purge if @qna.images.attached?
    @qna.update!(qna_params)

    respond_to :json
  end

  def destroy
    @qna = Qna.find(params[:id])
    @qna.destroy!

    redirect_to "#{qnas_path}"
  end

  private

  def qna_params
    params.require(:qna).permit(
      :question, :answer_1, :answer_2, :answer_3, :answer_4, :answer_5, :images,
      tag_ids: []
    )
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  def index
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
  end
end

app/controllers/yayplus1_controller.rb
class Yayplus1Controller < ApplicationController
  def index; end
end

app/controllers/yodatepicker_controller.rb
class YodatepickerController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_blank(body, url_options = {}, html_options = {})
    link_to(body, url_options, html_options.merge(target: '_blank'))
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/highlighter_helper.rb
module HighlighterHelper
  def options_for_language(selected_lang)
    selected = selected_lang.blank? ? '' : selected_lang
    options = Rouge::Lexer.all.map(&:tag).sort
    options_for_select(options, selected)
  end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/dashboard/index.html.haml
= content_for :title, 'Symbit - Home of YAY!'
%div.container-fluid.symbit-dashboard

  = render partial: 'shared/header', locals: {page_title: 'Symbit'}

  %div.container-fluid
    %p= link_to 'Code Syntax Highlighter', 'highlighter'
    %p= link_to 'Yodatepicker Datepicker / Calendar', 'yodatepicker'
    %p= link_to 'YayPlus1 Ratings', 'yayplus1'
    %p= link_to 'Kwizzy Quizzes', 'quizzes'

  - github_link = 'https://github.com/captainmarkos/symbit'
  = render partial: 'shared/footer', locals: {github_link: github_link}

app/views/highlighter/index.html.haml
:javascript

  var BASE_URL = 'https://salty-everglades-63319.herokuapp.com';

  $(document).ready(function() {
    var command = 'curl "https://salty-everglades-63319.herokuapp.com/highlighter/rouge" ' +
                  '--data "text=var foo = function() {\\n    console.log(\"Hello\");\\n};\\n' +
                  '&language=javascript"';

    console.log('--> command: ', command);
    $('#curl_example').text(command);
  });

  function rouge_request(prod_env) {
    var select_list = document.getElementById('language');
    var lang = language.options[language.selectedIndex].value;

    var raw_code = $('#code_to_highlight').val();
    var rouge_url = "#{rouge_highlighter_index_path}";

    if(prod_env || prod_env === 'true') {
        rouge_url = BASE_URL + "#{rouge_highlighter_index_path}"
    }

    console.log('--> rouge_url: ', rouge_url);

    $.ajax({
      method: 'POST',
      url: rouge_url,
      data: { text: raw_code, language: lang }
    })
    .done(function(response) {
      //console.log('--> response: ', response);
      $('#pretty_code').html(response.highlighted_text);
      $('#pretty_markup').text(response.highlighted_text);
      $('#hidden_markup_row').css('display', 'inline');
    })
    .fail(function() {
      alert('$.ajax() failed\nurl: ' + rouge_url);
    });
  }

= content_for :title, 'Code Syntax Highlighter'

%div.container-fluid.symbit-highlighter
  - page_title = 'Code Syntax Highlighter'
  = render partial: 'shared/header', locals: {page_title: page_title}

  %table.table
    %tr
      %td{ colspan: 2 }
        - prod_env = Rails.env.production?
        = 'Select a language:'
        = select_tag :language, options_for_language(params[:language])
        = button_tag "Make it Pretty", onclick: "rouge_request(#{prod_env});"
    %tr
      %td
        = text_area_tag :code_to_highlight, nil, class: 'code-to-highlight'
      %td
        %pre#pretty_code.highlight-github
    %tr
      %td{ colspan: 2 }
        %div#hidden_markup_row
          = 'Include these styles with the markup below to have your own highlighted code syntax: '
          = link_to_blank 'https://raw.githubusercontent.com/captainmarkos/symbit/master/app/assets/stylesheets/rouge_github.scss', 'https://raw.githubusercontent.com/captainmarkos/symbit/master/app/assets/stylesheets/rouge_github.scss'
          = text_area_tag :pretty_markup, nil
    %tr
      %td{ colspan: 2 }
        = 'A POST request will return the markup, see example below.'
        %br/
        = 'Use this stylesheet for the markup returned:'
        = link_to_blank 'https://raw.githubusercontent.com/captainmarkos/symbit/master/app/assets/stylesheets/rouge_github.scss', 'https://raw.githubusercontent.com/captainmarkos/symbit/master/app/assets/stylesheets/rouge_github.scss'
        %pre#curl_example

  %div.container-fluid
    Syntax highlighting thanks to
    = link_to 'https://github.com/jneen/rouge', 'https://github.com/jneen/rouge'

  - github_link = 'https://github.com/captainmarkos/symbit'
  = render partial: 'shared/footer', locals: {github_link: github_link}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title
      = yield(:title)
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Source Code Pro'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag 'favicon.ico'
  %body
    = yield

    :javascript
      $(document).ready(function() {
        $('.inline-update').inlineUpdate();
      });

app/views/qnas/_form.html.haml
%div.container-fluid
  %div.row.row-content
    = form_with(scope: :qna, model: @qna, class: 'form-inline') do |f|

      %div.form-group.row.mt-4
        %div.col-lg-4.col-md-6.col-sm-12
          %label.sr-only{ for: 'question'}= 'Question'
          = f.text_area :question, { class: 'form-control', 'placeholder' => 'Question' }

        %div.col-lg-4.col-md-6.col-sm-12
          %label{ for: 'images'}
          - if @qna.present? && @qna.images.attached?
            = image_tag @qna.images.first, style: 'max-width: 120px; max-height: 80px;'
          - else
            = image_tag '/assets/octobiwan.png', style: 'max-width: 120px; max-height: 80px;'
          = f.file_field :images, accept: 'image/png,image/gif,image/jpeg,image/jpg'

      %div.form-group.row.mt-4
        %div.col-lg-4.col-md-6.col-sm-12
          %label.sr-only{ for: 'answer_1'}= 'Answer 1'
          = f.text_area :answer_1, { class: 'form-control', 'placeholder' => 'Answer 1' }

      %div.form-group.row.mt-4
        %div.col-lg-4.col-md-6.col-sm-12
          %label.sr-only{ for: 'answer_2'}= 'Answer 2'
          = f.text_area :answer_2, { class: 'form-control', 'placeholder' => 'Answer 2' }

      %div.form-group.row.mt-4
        %div.col-lg-4.col-md-6.col-sm-12
          %label.sr-only{ for: 'answer_3'}= 'Answer 3'
          = f.text_area :answer_3, { class: 'form-control', 'placeholder' => 'Answer 3' }

      %div.form-group.row.mt-4
        %div.col-lg-4.col-md-6.col-sm-12
          %label.sr-only{ for: 'answer_4'}= 'Answer 4'
          = f.text_area :answer_4, { class: 'form-control', 'placeholder' => 'Answer 4' }

      %div.form-group.row.mt-4
        %div.col-lg-4.col-md-6.col-sm-12
          %label.sr-only{ for: 'answer_5'}= 'Answer 5'
          = f.text_area :answer_5, { class: 'form-control', 'placeholder' => 'Answer 5' }

      %div.form-group.row.mt-4
        %div.col-lg-4.col-md-6.col-sm-12
          %label.sr-only{ for: 'tags'}= 'Tags'
          = f.collection_select(:tag_ids, Tag.all, :id, :name, {}, { multiple: true, class: 'form-control' })
          = f.hidden_field(:target_type, value: 'Qna')
          = f.hidden_field(:correct_answer, value: 'answer_1')

      %div.form-group.row.mt-4
        %div.col-sm-3
          = f.button 'Save', { class: 'btn btn-primary btn-sm' }
          = f.button 'Reset', { name: 'reset', type: 'reset', class: 'btn btn-primary btn-sm' }

app/views/qnas/_table.html.haml
%script{ type: 'text/javascript' }
  :plain
    var refresh_image = function() {
      location.reload();
    };

%div.container-fluid
  %div.row.row-content
    %div.col-12.col-sm-12
      %div.table

        %table.table.table-striped
          %thead.thead-dark
            %tr
              %th
              %th= 'ID'
              %th= 'IMAGE'
              %th= 'QUESTION'
              %th= 'ANSWER 1'
              %th= 'ANSWER 2'
              %th= 'ANSWER 3'
              %th= 'ANSWER 4'
          %tbody
            - @qnas.each do |qna|
              %tr
                %td= link_to 'Delete', qna_path(id: qna.id), method: :delete
                %td= qna.id

                %td{ style: 'text-align: center;' }
                  - # binding.pry
                  - if qna.images.attached?
                    = image_tag qna.images.first, style: 'max-width: 120px; max-height: 80px;'
                  - else
                    = image_tag '/assets/octobiwan.png', style: 'max-width: 120px; max-height: 80px;'
                  %br
                  = form_with(scope: :qna, model: qna, :html => { id: qna.id, onsubmit: "refresh_image();" } ) do |f|
                    = f.file_field :images, { id: "qna_image_#{qna.id}", accept: 'image/png,image/gif,image/jpeg,image/jpg' }
                    = f.button 'Save', { class: 'btn btn-primary btn-sm' }

                %td= text_field_tag 'qna[question]', qna.question, class: 'form-control inline-update', 'data-path' => qna_path(id: qna.id)
                %td= text_field_tag 'qna[answer_1]', qna.answer_1, class: 'form-control inline-update', 'data-path' => qna_path(id: qna.id)
                %td= text_field_tag 'qna[answer_2]', qna.answer_2, class: 'form-control inline-update', 'data-path' => qna_path(id: qna.id)
                %td= text_field_tag 'qna[answer_3]', qna.answer_3, class: 'form-control inline-update', 'data-path' => qna_path(id: qna.id)
                %td= text_field_tag 'qna[answer_4]', qna.answer_4, class: 'form-control inline-update', 'data-path' => qna_path(id: qna.id)

app/views/qnas/index.html.haml
%div.container-fluid

  %div.row.row-header
    %div.col-12.col-sm-6
      %h3= 'Question and Answers'

= render partial: 'form'

= render partial: 'table'

app/views/quizzes/index.html.haml
%div.container-fluid
  %div.row.row-header
    %div.col-lg-4.col-md-6.col-sm-12
      %h3= 'Question and Answers'

%div.container-fluid
  %div.row.row-content
    = form_with(scope: :quiz, model: @quiz, class: 'form-inline') do |f|

      %div.form-group.row.mt-4
        %div.col-lg-4.col-md-6.col-sm-12
          %label.sr-only{ for: 'question'}= 'Question'
          = f.text_area :question, { class: 'form-control', 'placeholder' => 'Question' }

        %div.col-lg-4.col-md-6.col-sm-12
          %label.sr-only{ for: 'images'}
          - if @qna.present? && @qna.images.attached?
            = image_tag @qna.images.first, style: 'max-width: 120px; max-height: 80px;'
          - else
            = image_tag '/assets/octobiwan.png', style: 'max-width: 120px; max-height: 80px;'
          = f.file_field :images, accept: 'image/png,image/gif,image/jpeg,image/jpg'

      %div.form-group.row.mt-4
        %div.col-lg-4.col-md-6.col-sm-12
          %label.sr-only{ for: 'answer_1'}= 'Answer 1'
          = f.text_area :answer_1, { class: 'form-control', 'placeholder' => 'Answer 1' }

app/views/shared/_footer.html.haml
%div.container-fluid.footer
  %hr/
  = image_tag('octobiwan_100x100.png', class: 'octobiwan')
  = image_tag('GitHub-Logo.png', class: 'github-logo')
  = link_to "#{github_link}", "#{github_link}"

app/views/shared/_header.html.haml
- page_title = 'Symbit' if page_title.blank?
- subtitle = '' if subtitle.blank?
%div.container-fluid
  %center
    %h2= page_title
    %p= subtitle
    %p Yay for fun stuff!
  %hr/

app/views/tags/index.html.haml
%h1 Tags#index
%p Find me in app/views/tags/index.html.haml

app/views/yayplus1/index.html.haml
= javascript_include_tag 'yayplus1.js'

:css
  #yayplus1_0 {
    cursor: pointer;
  }

  #yayplus1_1 {
    cursor: pointer;
  }

   #yayplus1_2 {
    cursor: pointer;
  }

   #yayplus1_3 {
    cursor: pointer;
  }

   #yayplus1_4 {
    cursor: pointer;
  }

%h2{style: 'text-align: center;'} Yayplus1 Ratings
%hr

%div#yayplus1-ratings

:javascript

  var ratings = new YayPlus1();

  $(document).ready(function() {

    ratings.create('yayplus1-ratings', 5);

  });

app/views/yodatepicker/index.html.haml
= javascript_include_tag 'yodatepicker/dist/yodatepicker.js'
- # To load the file assets/javascripts/yodatepicker/dist/yodatepicker.js

:javascript

  $(document).ready(function() {

    var activity_calendar_en = yodatepicker({
        dp_id_name: 'dp_activity_calendar_en',
        id_name: 'activity_datepicker_en',
        months_to_display: 1,
        use_date_range: false,
        dow_heading: 'short_name',
        close_onselect: false,
        min_date: new Date(),
        max_date: '1Y',
        locale: 'en',

        // navigation arrow icons and colors
        prev_fa_class: 'fas fa-chevron-circle-left',
        next_fa_class: 'fas fa-chevron-circle-right'
    });

    var activity_calendar_es = yodatepicker({
        dp_id_name: 'dp_activity_calendar_es',
        id_name: 'activity_datepicker_es',
        months_to_display: 1,
        use_date_range: false,
        dow_heading: 'full_name',
        close_onselect: false,
        min_date: new Date(),
        max_date: '1Y',
        locale: 'es',

        // navigation arrow icons and colors
        prev_fa_class: 'fas fa-chevron-circle-left',
        next_fa_class: 'fas fa-chevron-circle-right'
    });

    var activity_calendar_fr = yodatepicker({
        dp_id_name: 'dp_activity_calendar_fr',
        id_name: 'activity_datepicker_fr',
        months_to_display: 1,
        use_date_range: false,
        dow_heading: 'short_name',
        close_onselect: false,
        min_date: new Date(),
        max_date: '1Y',
        locale: 'fr',

        // navigation arrow icons and colors
        prev_fa_class: 'fas fa-chevron-circle-left',
        next_fa_class: 'fas fa-chevron-circle-right'
    });

    activity_calendar_en.show();
    activity_calendar_es.show();
    activity_calendar_fr.show();

  });

= content_for :title, 'Yodatepicker - Javascript Datepicker / Calendar'

%div.container-fluid.symbit-yodatepicker
  - page_title = 'Yodatepicker'
  - subtitle = 'Pure Javascrpt Datepicker / Calendar'
  = render partial: 'shared/header', locals: {page_title: page_title, subtitle: subtitle}

  %div.container-fluid
    %div.calendar-container
      %div#dp_activity_calendar_en
      %br/
      %div
        Select a Date:
        = text_field_tag 'activity_datepicker_en'

    %div.calendar-container
      %div#dp_activity_calendar_es
      %br/
      %div
        Select a Date:
        = text_field_tag 'activity_datepicker_es'

    %div.calendar-container
      %div#dp_activity_calendar_fr
      %br/
      %div
        Select a Date:
        = text_field_tag 'activity_datepicker_fr'

  - github_link = 'https://github.com/captainmarkos/yodatepicker'
  = render partial: 'shared/footer', locals: {github_link: github_link}